# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_gallery', '0006_auto_20180411_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='src',
        ),
    ]
